{% set name = "conda-spawn" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9160a6da2fdab03c23819fdaacbe3041da6f2979e2fcbb6f29629ee90f01c108

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >={{ python_min }}
    - conda >=23.9.0
    - pexpect
    - shellingham

test:
  requires:
    - python {{ python_min }}
  imports:
    - conda_spawn
    - conda_spawn.main
  commands:
    - python -m conda spawn --help

about:
  home: https://github.com/conda-incubator/conda-spawn
  license: MIT AND BSD-3-Clause
  license_file: LICENSE
  summary: Activate conda environments in new shell processes
  dev_url: https://github.com/conda-incubator/conda-spawn

extra:
  recipe-maintainers:
    - jaimergp
